server:
  port: 5000

telegram:
  # TODO: Will be updated after finishing
  token: TODO
  webhook: TODO

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  datasource:
    url: jdbc:mariadb://localhost:3307/telegram
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy