server:
  port: 5000

telegram:
  userName: poe_consult_light_bot
  token: AAGu7SSMgtIjaevHU9Zwqcdg9ksDbvwSNU0
  webhook: https://2d0a-89-73-4-11.ngrok-free.app
  adminId: 6983431014

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  datasource:
    url: jdbc:mariadb://localhost:3306/poe
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy