services:
  aggregator-database:
    image: mariadb:11.2.5@sha256:57a30f335f24bce78482dcb14b10030dccd871b0fc6dce2568a17348e880af53
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: aggregator

  telegram-database:
    image: mariadb:11.2.5@sha256:57a30f335f24bce78482dcb14b10030dccd871b0fc6dce2568a17348e880af53
    restart: always
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: telegram
