services:
  aggregator-database:
    image: mariadb:11.2.5@sha256:ab3f5b186596f1b6cf7cfece60cc254a3eef08e032e3099ef719b5429d0be90a
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: aggregator

  telegram-database:
    image: mariadb:11.2.5@sha256:ab3f5b186596f1b6cf7cfece60cc254a3eef08e032e3099ef719b5429d0be90a
    restart: always
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: telegram
