x-common: &mariadb-config
  image: mariadb:11.2.5@sha256:1363d4688aed0a0c3ddacb6e1b0a93dcfd765e557cb05e207b46bc8c60e376af
  restart: always

services:
  a8r-mariadb:
    <<: *mariadb-config
    ports: ["3306:3306"]
    environment:
      MARIADB_DATABASE: a8r
      MARIADB_ROOT_PASSWORD: root

  telegram-mariadb:
    <<: *mariadb-config
    ports: ["3307:3306"]
    environment:
      MARIADB_DATABASE: telegram
      MARIADB_ROOT_PASSWORD: root
