services:

  aggregator-database:
    image: mariadb:11.2.4@sha256:7830bb0df5a8eff943f32eb5455924570a23c7083e2d21a16f0377a5e50a8a4d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: aggregator

  telegram-database:
    image: mariadb:11.2.4@sha256:7830bb0df5a8eff943f32eb5455924570a23c7083e2d21a16f0377a5e50a8a4d
    restart: always
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: telegram