server:
  port: 8080

  ### Telegram Bot SETTINGS
config:
  url: https://poe.ninja/api/data/itemoverview
  league: Ancestor

eventservice:
  period: 600000

  ### Database SETTINGS
  #spring.datasource.driver-class-name=org.postgresql.Driver
  #spring.datasource.url=jdbc:postgresql://localhost:5432/telegramUsers
  #spring.datasource.username=postgres
  #spring.datasource.password=password

  #spring.jpa.hibernate.ddl-auto=update
spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  datasource:
    url: jdbc:mariadb://localhost:3306/poe
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.show-sql=true