server:
  port: 5000

  ### Telegram Bot SETTINGS
  config:
    url: https://poe.ninja/api/data/itemoverview
    league: Ancestor

  eventservice:
    period: 600000

  ### Database SETTINGS
  #spring.datasource.driver-class-name=org.postgresql.Driver
  #spring.datasource.url=jdbc:postgresql://localhost:5432/telegramUsers
  #spring.datasource.username=postgres
  #spring.datasource.password=password

  #spring.jpa.hibernate.ddl-auto=update
  spring:
    datasource:
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/service
    driver-class-name: org.mariadb.jdbc.Driver
#spring.jpa.show-sql=true