server:
  port: 8080

aggregator:
  ninja:
    base-url: https://poe.ninja
    route: /api/data/itemoverview
    league: Standard

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  datasource:
    url: jdbc:mariadb://localhost:3306/aggregator
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
