server:
  port: 8080

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration/common,classpath:db/migration/${ENV_VARIABLE}

  datasource:
    url: jdbc:mariadb://localhost:3306/a8r
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
