name: 'Nightly Tests'

on:
  workflow_dispatch:

jobs:
  run-tests-on-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle-task: [ 'check' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          cache: 'gradle'
          java-version: '17'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8
      - name: Run the unit tests
        run: gradle :modules:tests:${{ matrix.gradle-task }} --no-parallel --no-daemon --console=plain
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-linux-${{matrix.gradle-task}}
          retention-days: 14
          path: |
            **/build/reports
            **/build/test-results
