name: "Nightly Tests"

on:
  workflow_dispatch:

jobs:
  run-tests-on-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle-task: ["check"]
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Check repository over Prettier
        uses: actionsx/prettier@3d9f7c3fa44c9cb819e68292a328d7f4384be206 # v3
        with:
          args: --check --ignore-unknown '**/*.*'
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: "corretto"
          cache: "gradle"
          java-version: "17"
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3
        with:
          gradle-version: 8.9
      - name: Run the Integration Tests
        run: gradle :modules:tests:${{ matrix.gradle-task }} --no-parallel --no-daemon --console=plain
      - uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4
        if: always()
        with:
          name: test-report-linux-${{ matrix.gradle-task }}
          retention-days: 14
          path: |
            **/build/reports
            **/build/test-results
