name: "Test Report"
on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          run-id: ${{ github.event.workflow_run.id }}
      - uses: dorny/test-reporter@v1
        with:
          name: "Test report ${{matrix.os}} ${{matrix.gradle-task}}"
          path: "**/build/test-results/**/TEST-*.xml"
          reporter: java-junit
