name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'Run tests' ]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Download artifacts
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          run-id: ${{ github.event.workflow_run.id }}
      - uses: dorny/test-reporter@v1
        with:
#          artifact: /test-report-(.*)-(.*)/
#          name: 'Test report: $1 $2'
          name: 'Test report'
          path: '**/build/test-results/**/TEST-*.xml'
          reporter: java-junit