name: "Run tests"
on:
  push:
    branches:
      - main
  pull_request:
env:
  IS_REMOTE: ${{ secrets.IS_REMOTE }}

jobs:
  run-tests-on-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle-task: ["check"]
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Check repository over Prettier
        uses: actionsx/prettier@3d9f7c3fa44c9cb819e68292a328d7f4384be206 # v3
        with:
          args: --check --ignore-unknown '**/*.*'
      - name: Set up JDK
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          distribution: "corretto"
          cache: "gradle"
          java-version: "17"
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4
        with:
          gradle-version: "8.10"
      - name: Run the unit tests
        run: gradle ${{ matrix.gradle-task }} --no-parallel --no-daemon --console=plain
      - uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        if: always()
        with:
          name: test-report-linux-${{ matrix.gradle-task }}
          retention-days: 14
          path: |
            **/build/reports
            **/build/test-results
